# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832b59163e9983356762e7ecf320523c5b83ed29fdd8680178a9e78510689bd21070a1a88b4f7fb1a702fbe65ef9f22ca183794ffc6d512fdc259a78196262f8

test:
  secret_key_base: be471c7d4d05fec7497bd7cb0468e71d4e05d6e885e2e0a746f3e74b0e84ecb6a2720eba49b80c43c2a22252f992e9c82a03fed918b32f49c76b8fb2c1b639bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
